#cloud-config
packages:
  - docker

runcmd:
  - systemctl start docker
  - docker run -d --name kong -v "/opt/kong/:/usr/local/kong/declarative" -e "KONG_DATABASE=off" -e "KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml" -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" -e "KONG_PROXY_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" -p 8000:8000 -p 8443:8443 -p 8001:8001 -p 8444:8444 kong:latest

write_files:
  - path: /etc/motd
    content: |
      Hello, this instance is initialized w/ cloud-init
      Welcome!!
    owner: root:root
    permissions: '0644'

  - path: /opt/kong/kong.yml
    content: |
      _format_version: "1.1"

      services:
      - name: example_service
        url: http://mockbin.org
        routes:
        - name: mocking
          paths:
          - /mock
    permissions: '0644'

timezone: "Asia/Kolkata"